name: fetch-from-simtropolis
description: Fetches a file from Simtropolis and generates metadata from it
inputs:
  url:
    description: The url to parse the medata from
    required: true
  require-metadata:
    description: Whether a metadata.yaml file is required to add the package. Useful to turn this off for testing.
    type: boolean
    default: true
outputs:
  message:
    description: The commit message that will be used by the GitHub actions bot

runs:
  using: 'node20'
  main: 'action.js'
