name: Deploy Simtropolis channel

on:
  workflow_run:
    workflows:
      - Fetch Simtropolis package
    types:
      - completed

jobs:
  deploy:
    uses: memo33/sc4pac-actions/.github/workflows/sc4pac-channel.yaml@main
    with:
      path: src/yaml
      channel-label: Simtropolis
      deploy-repository: sebamarynissen/simtropolis-channel
      use-stex-api: true
      lint: false
    secrets:
      stex-api-key: ${{ secrets.STEX_API_KEY }}
    permissions:
      pages: write
      id-token: write
