# IMPORTANT! If you change this name, you should change it in "deploy.yaml" as 
# well as it references it by name!
name: Add package from Simtropolis
on:
  workflow_dispatch:
    inputs:
      url:
        description: URL or file id
        required: true
      require-metadata:
        description: Require metadata.yaml
        type: boolean
        default: true

jobs:
  add-from-simtropolis:
    runs-on: ubuntu-latest
    permissions: write-all

    env:
      SC4PAC_SIMTROPOLIS_COOKIE: ${{ secrets.SC4PAC_SIMTROPOLIS_COOKIE }}
      STEX_API_KEY: ${{ secrets.STEX_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.STEX_BOT_TOKEN }}
      GITHUB_OWNER: ${{ github.repository_owner }}
      GITHUB_REPO: ${{ github.event.repository.name }}

    steps:
      - uses: actions/checkout@v4
        # Explicitly checkout the main branch because the commit that triggered 
        # the former workflow does not yet include the latest metadata! It's the 
        # former action that has committed that new metadata!
        with:
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Configure Git user
        run: |
          git config --global user.name "simtropolis-bot"
          git config --global user.email "simtropolis-bot@users.noreply.github.com"
      - run: npm ci
      - id: fetch
        uses: ./actions/fetch
        with:
          url: ${{ github.event.inputs.url }}
          require-metadata: ${{ github.events.inputs.require-metadata }}
