# IMPORTANT! If you change this name, you should change it in "deploy.yaml" as 
# well as it references it by name!
name: Add package from Simtropolis
on:
  workflow_dispatch:
    inputs:
      url:
        description: URL or file id
        required: true
      require-metadata:
        description: Require metadata.yaml
        type: boolean
        default: true

jobs:
  add-from-simtropolis:
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      prs: ${{ steps.fetch.outputs.prs }}
    env:
      SC4PAC_SIMTROPOLIS_COOKIE: ${{ secrets.SC4PAC_SIMTROPOLIS_COOKIE }}
      STEX_API_KEY: ${{ secrets.STEX_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OWNER: ${{ github.repository_owner }}
      GITHUB_REPO: ${{ github.event.repository.name }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - run: npm ci
      - id: fetch
        uses: ./actions/fetch
        with:
          url: ${{ github.event.inputs.url }}
          require-metadata: ${{ github.events.inputs.require-metadata }}

  lint:
    needs: add-from-simtropolis
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions: write-all
    strategy:
      max-parallel: 1
      matrix:
        pr: ${{ fromJson(needs.add-from-simtropolis.outputs.prs) }}
    steps:
      - name: Set pending status
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ matrix.pr.sha }}',
              state: 'pending',
              context: 'repository_dispatch',
              description: 'Running lint',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID}`
            });
      - name: Check out repository
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.pr.ref }}
      - name: Lint
        id: lint
        uses: memo33/sc4pac-actions/actions/lint@main
        with:
          path: src/yaml
      - name: Set status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ matrix.pr.sha }}',
              state: '${{ steps.lint.outcome }}',
              context: 'repository_dispatch',
              description: 'Lint successful',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID}`
            });

      - name: Merge PR
        run: gh pr merge ${{ matrix.pr.number }} --merge

  deploy:
    needs: lint
    runs-on: ubuntu-latest
    if: ${{ needs.lint.result == 'success' }}
    uses: sebamarynissen/sc4pac-actions/.github/workflows/sc4pac-channel.yaml@main
    with:
      ref: main
      path: src/yaml
      channel-label: Simtropolis
      deploy-repository: sebamarynissen/simtropolis-channel
      use-stex-api: false
    permissions:
      pages: write
      id-token: write
