name: Lint

on:
  push:
    branches:
      - 'package/*'
  repository_dispatch:
    types: [lint]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo ${{ github.event.client_payload.ref }}
          echo ${{ github.event.client_payload.pr }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Lint
        uses: memo33/sc4pac-actions/actions/lint@main
      - name: Set status
        uses: actions/github-script@v7
        with:
          script: |
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              context: 'repository_dispatch',
              description: 'Lint successful',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID}`
            });
